"""Initial migration

Revision ID: 56f2e20aacc7
Revises: 
Create Date: 2025-12-08 20:25:04.727629

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56f2e20aacc7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE IF EXISTS transactiontype CASCADE")
    op.execute("DROP TYPE IF EXISTS currency CASCADE")
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('FUND', 'CONVERT', 'WITHDRAW', name='transactiontype'), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'MXN', name='currency'), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('from_currency', sa.Enum('USD', 'MXN', name='currency'), nullable=True),
    sa.Column('to_currency', sa.Enum('USD', 'MXN', name='currency'), nullable=True),
    sa.Column('from_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('to_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('fx_rate', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_transaction_type'), 'transaction', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_transaction_user_id'), 'transaction', ['user_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'MXN', name='currency'), nullable=False),
    sa.Column('balance', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'currency', name='unique_user_currency')
    )
    op.create_index(op.f('ix_wallet_currency'), 'wallet', ['currency'], unique=False)
    op.create_index(op.f('ix_wallet_user_id'), 'wallet', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_user_id'), table_name='wallet')
    op.drop_index(op.f('ix_wallet_currency'), table_name='wallet')
    op.drop_table('wallet')
    op.drop_table('user')
    op.drop_index(op.f('ix_transaction_user_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_transaction_type'), table_name='transaction')
    op.drop_table('transaction')
    op.execute("DROP TYPE IF EXISTS transactiontype CASCADE")
    op.execute("DROP TYPE IF EXISTS currency CASCADE")
    # ### end Alembic commands ###
